### ISSUE TITLE
Assertion Error during distributed training when using small dataset

### ISSUE THREAD

**Issue by Saurav-D** [Unity-Technologies/datasetinsights#106]
**Describe the Bug:**
When running train pipeline on kubeflow using a small dataset (12 binary files). I got Assertion error. I have attached the tracback.

**How to Reproduce?**
Run train pipeline using any small dataset around (50 images)

**What did you expect to happen:**
Complete train pipeline successfully.

**Console logs / stack traces**
```
INFO | 2020-09-30 13:41:32 | root | MainThread | [epoch-0-evaluate-time] elapsed time: 0.0016 seconds.

Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "datasetinsights/__main__.py", line 36, in <module>
    entrypoint()
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/datasetinsights/datasetinsights/commands/train.py", line 123, in cli
    estimator.train(train_data=train_data, val_data=val_data)
  File "/datasetinsights/datasetinsights/estimators/faster_rcnn.py", line 197, in train
    train_sampler=train_sampler,
  File "/datasetinsights/datasetinsights/estimators/faster_rcnn.py", line 255, in train_loop
    label_mappings=label_mappings,
  File "/usr/local/lib/python3.7/dist-packages/torch/autograd/grad_mode.py", line 49, in decorate_no_grad
    return func(*args, **kwargs)
  File "/datasetinsights/datasetinsights/estimators/faster_rcnn.py", line 393, in evaluate_per_epoch
    for i, (images, targets) in enumerate(tqdm(data_loader)):
  File "/usr/local/lib/python3.7/dist-packages/tqdm/std.py", line 1130, in __iter__
    for obj in iterable:
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/dataloader.py", line 345, in __next__
    data = self._next_data()
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/dataloader.py", line 384, in _next_data
    index = self._next_index()  # may raise StopIteration
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/dataloader.py", line 339, in _next_index
    return next(self._sampler_iter)  # may raise StopIteration
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/sampler.py", line 200, in __iter__
    for idx in self.sampler:
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/distributed.py", line 55, in __iter__
    assert len(indices) == self.total_size

AssertionError

Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.7/dist-packages/torch/distributed/launch.py", line 263, in <module>
    main()
  File "/usr/local/lib/python3.7/dist-packages/torch/distributed/launch.py", line 259, in main
    cmd=cmd)
subprocess.CalledProcessError: Command '['/usr/local/bin/python', '-u', 'datasetinsights', 'train', '--config=datasetinsights/configs/faster_rcnn_synthetic.yaml', '--train-data=/data', '--val-data=/data', '--tb-log-dir=gs://thea-dev/runs/b61cf806-fe07-4435-9877-4a24b77e6b60/tb', '--checkpoint-dir=gs://thea-dev/runs/b61cf806-fe07-4435-9877-4a24b77e6b60/checkpoints']' returned non-zero exit status 1.

```

**Environment:**

- datasetinsights version: `datasetinsights:latest`
- _Environment_: Kubeflow

**Comment by 86sanj** [comment]
We don't support training in the current repo after https://github.com/Unity-Technologies/datasetinsights/issues/143 release. So closing this issue.
