### ISSUE TITLE
No space left when running training with more than 10 epochs

### ISSUE THREAD

**Issue by Saurav-D** [Unity-Technologies/datasetinsights#107]
**Describe the Bug:**
I'm getting `OSError: [Errno 28] No space left on device` when I'm running train pipeline on kubeflow with epochs more than 10 with dataset having ~2k images.

I think it is because the shared memory (temp file storage) gets filled while writing tensorboard files. I have attached traceback and screenshots of memory of file system during training.

**Console logs / stack traces**
```
Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "datasetinsights/__main__.py", line 36, in <module>
    entrypoint()
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/datasetinsights/datasetinsights/commands/train.py", line 123, in cli
    estimator.train(train_data=train_data, val_data=val_data)
  File "/datasetinsights/datasetinsights/estimators/faster_rcnn.py", line 197, in train
    train_sampler=train_sampler,
  File "/datasetinsights/datasetinsights/estimators/faster_rcnn.py", line 255, in train_loop
    label_mappings=label_mappings,
  File "/usr/local/lib/python3.7/dist-packages/torch/autograd/grad_mode.py", line 49, in decorate_no_grad
    return func(*args, **kwargs)
  File "/datasetinsights/datasetinsights/estimators/faster_rcnn.py", line 424, in evaluate_per_epoch
    self.log_metric_val(label_mappings, epoch)
  File "/datasetinsights/datasetinsights/estimators/faster_rcnn.py", line 456, in log_metric_val
    f"val/{metric_name}-per-class", label_results, epoch
  File "/usr/local/lib/python3.7/dist-packages/tensorboardX/writer.py", line 451, in add_scalars
    fw = FileWriter(logdir=fw_tag)
  File "/usr/local/lib/python3.7/dist-packages/tensorboardX/writer.py", line 95, in __init__
    logdir, max_queue, flush_secs, filename_suffix)
  File "/usr/local/lib/python3.7/dist-packages/tensorboardX/event_file_writer.py", line 105, in __init__
    self._event_queue = multiprocessing.Queue(max_queue_size)
  File "/usr/lib/python3.7/multiprocessing/context.py", line 102, in Queue
    return Queue(maxsize, ctx=self.get_context())
  File "/usr/lib/python3.7/multiprocessing/queues.py", line 48, in __init__
    self._sem = ctx.BoundedSemaphore(maxsize)
  File "/usr/lib/python3.7/multiprocessing/context.py", line 87, in BoundedSemaphore
    return BoundedSemaphore(value, ctx=self.get_context())
  File "/usr/lib/python3.7/multiprocessing/synchronize.py", line 145, in __init__
    SemLock.__init__(self, SEMAPHORE, value, value, ctx=ctx)
  File "/usr/lib/python3.7/multiprocessing/synchronize.py", line 59, in __init__
    unlink_now)
OSError: [Errno 28] No space left on device
```

**Screenshots**
This is the screenshots of command `df -h` inside the train container of the pipeline.

![image](https://user-images.githubusercontent.com/26328148/95005862-2c457880-05b2-11eb-8c74-b6814310ec0b.png)
![image](https://user-images.githubusercontent.com/26328148/95005865-2fd8ff80-05b2-11eb-8a33-ebdc51b860a9.png)
![image](https://user-images.githubusercontent.com/26328148/95005868-32d3f000-05b2-11eb-8277-153da000cbed.png)

`/dev/shm` get used up to 99% then I get the error on kubeflow pipeline and then it gets empty automatically.

**Comment by Saurav-D** [comment]
Adding `emptyDir` volume and mounting `/dev/shm` to it in the pipeline resolves the issue.

**Comment by Saurav-D** [comment]
Current workaround:

```
train.add_volume(
        k8s_client.V1Volume(
            name="dshm",
            empty_dir=k8s_client.V1EmptyDirVolumeSource(medium="Memory"),
        )
    )
train.add_volume_mount(
    k8s_client.V1VolumeMount(name="dshm", mount_path="/dev/shm")
)
```

Adding the above code to the trainOp in the pipeline resolves the issue.

**Comment by 86sanj** [comment]
We don't support training in the current repo after https://github.com/Unity-Technologies/datasetinsights/issues/143 release. So closing this issue.
