### ISSUE TITLE
FileExistsError when writing metrics

### ISSUE THREAD

**Issue by Saurav-D** [Unity-Technologies/datasetinsights#114]
**Describe the Bug:**
I get file exists error when I try to save metrics on local file system on Kubeflow. This error hangs the kubeflow training pipeline.

**How to Reproduce?**
Try to run train pipeline with `tb_log_dir` as `/run/tb/`

**What did you expect to happen:**
Complete training.

**Console logs / stack traces**
```
KeyError: '/runs/465893c5-8006-4aa6-bf7d-125e4d58d5d5/tb/val/APIOU50-per-class/drink_whippingcream_lucerne'
During handling of the above exception, another exception occurred:
fw = FileWriter(logdir=fw_tag)
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/tensorboardX/writer.py", line 95, in __init__
  File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    directory_check(self._logdir)
  File "/usr/local/lib/python3.7/dist-packages/tensorboardX/record_writer.py", line 51, in directory_check
    logdir, max_queue, flush_secs, filename_suffix)
  File "/usr/local/lib/python3.7/dist-packages/tensorboardX/event_file_writer.py", line 104, in __init__
    "__main__", mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    os.makedirs(path)
  File "/usr/lib/python3.7/os.py", line 221, in makedirs
    exec(code, run_globals)    
directory_check(self._logdir)  File "datasetinsights/__main__.py", line 36, in <module>
  File "/usr/local/lib/python3.7/dist-packages/tensorboardX/record_writer.py", line 51, in directory_check
    entrypoint()
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 829, in __call__
    os.makedirs(path)
  File "/usr/lib/python3.7/os.py", line 221, in makedirs
    mkdir(name, mode)
FileExistsError: [Errno 17] File exists: '/runs/465893c5-8006-4aa6-bf7d-125e4d58d5d5/tb/val/APIOU50-per-class/drink_orangejuice_minutemaid'
    mkdir(name, mode)
FileExistsError: [Errno 17] File exists: '/runs/465893c5-8006-4aa6-bf7d-125e4d58d5d5/tb/val/APIOU50-per-class/drink_orangejuice_minutemaid'
```

**Comment by Saurav-D** [comment]
This is the issue that I found on tensorboardX repo: https://github.com/lanpa/tensorboardX/issues/546

**Comment by Saurav-D** [comment]
It was solved in this PR: https://github.com/lanpa/tensorboardX/pull/556

**Comment by adason** [comment]
#99 related
