### ISSUE TITLE
convert command failing with unexpected argument

### ISSUE THREAD

**Issue by johnbrumley** [Unity-Technologies/datasetinsights#189]
**Describe the Bug:**
Using Colab Notebook to convert a perception dataset to COCO format. The CLI convert command fails with an error. 

**How to Reproduce?**
Running the convert command after installing via `!pip install git+https://github.com/Unity-Technologies/datasetinsights.git`

**What did you expect to happen:**
Conversion of the dataset.

**Console logs / stack traces**
Please wrap in [triple backticks (```)](https://help.github.com/en/articles/creating-and-highlighting-code-blocks) to make it easier to read.

```
Traceback (most recent call last):
  File "/usr/local/bin/datasetinsights", line 8, in <module>
    sys.exit(entrypoint())
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/datasetinsights/commands/convert.py", line 41, in cli
    transformer = get_dataset_transformer(format=format, input=input)
  File "/usr/local/lib/python3.7/dist-packages/datasetinsights/datasets/transformers/base.py", line 22, in get_dataset_transformer
    return transformer(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'input'
```

**Screenshots**
![image](https://user-images.githubusercontent.com/8105250/143811239-736945e6-373d-4304-a664-0e09c915596d.png)

**Anything else you would like to add:**
Fixed by modifying 'datasetinsights/commands/convert.py' line 41 to use keyword "data_root"  instead of "input"

```
transformer = get_dataset_transformer(format=format, data_root=input)
```

**Environment:**

Google Colab with current main branch of datasetinsights

**Comment by johnbrumley** [comment]
Looks like issue was fixed, Thanks!
