### ISSUE TITLE
tensorboardX import error

### ISSUE THREAD

**Issue by zookae** [Unity-Technologies/datasetinsights#41]
/kind bug

**Describe the Bug:**
After following the installation instructions in the contributing guide (https://github.com/Unity-Technologies/datasetinsights/blob/master/CONTRIBUTING.md) I hit an error when trying to run the datasetinsights cli example command. The error reports missing the tensorboardX module. This is unexpected as the I had installed the poetry lock file which should theoretically contain all the requirements.

**How to Reproduce?**
Follow the contributing guide step-by-step instructions. Attempt to run the example Faster R-CNN model using the CLI.

**What did you expect to happen:**
The Faster R-CNN model would run and report something about running.

**Console logs / stack traces**

```
% conda create -n di python=3.7
...
% conda activate di
% git clone https://github.com/Unity-Technologies/datasetinsights.git
% cd datasetinsights
% poetry install
Installing dependencies from lock file


Package operations: 175 installs, 0 updates, 0 removals

  - Installing decorator (4.4.2)
  - Installing ipython-genutils (0.2.0)
  - Installing six (1.15.0)
  - Installing zipp (3.1.0)
  - Installing attrs (19.3.0)
  - Installing importlib-metadata (1.7.0)
  - Installing parso (0.7.1)
  - Installing ptyprocess (0.6.0)
  - Installing pyparsing (2.4.7)
  - Installing pyrsistent (0.16.0)
  - Installing traitlets (4.3.3)
  - Installing wcwidth (0.2.5)
  - Installing appnope (0.1.0)
  - Installing backcall (0.2.0)
  - Installing jedi (0.17.2)
  - Installing jsonschema (3.2.0)
  - Installing jupyter-core (4.6.3)
  - Installing markupsafe (1.1.1)
  - Installing packaging (20.4)
  - Installing pexpect (4.8.0)
  - Installing pickleshare (0.7.5)
  - Installing prompt-toolkit (3.0.5)
  - Installing pycparser (2.20)
  - Installing pygments (2.6.1)
  - Installing python-dateutil (2.8.1)
  - Installing pyzmq (19.0.2)
  - Installing tornado (6.0.4)
  - Installing webencodings (0.5.1)
  - Installing bleach (3.1.5)
  - Installing cffi (1.14.1)
  - Installing defusedxml (0.6.0)
  - Installing entrypoints (0.3)
  - Installing ipython (7.17.0)
  - Installing jinja2 (2.11.2)
  - Installing jupyter-client (6.1.6)
  - Installing mistune (0.8.4)
  - Installing nbformat (5.0.7)
  - Installing pandocfilters (1.4.2)
  - Installing testpath (0.4.4)
  - Installing argon2-cffi (20.1.0)
  - Installing chardet (3.0.4)
  - Installing idna (2.10)
  - Installing ipykernel (5.3.4)
  - Installing nbconvert (5.6.1)
  - Installing prometheus-client (0.8.0)
  - Installing pyasn1 (0.4.8)
  - Installing send2trash (1.5.0)
  - Installing terminado (0.8.3)
  - Installing urllib3 (1.25.10)
  - Installing cachetools (4.1.1)
  - Installing notebook (6.1.1)
  - Installing oauthlib (3.1.0)
  - Installing protobuf (3.12.4)
  - Installing pyasn1-modules (0.2.8)
  - Installing requests (2.24.0)
  - Installing rsa (4.6)
  - Installing click (7.1.2)
  - Installing cycler (0.10.0)
  - Installing google-auth (1.20.0)
  - Installing googleapis-common-protos (1.52.0)
  - Installing heapdict (1.0.1)
  - Installing itsdangerous (1.1.0)
  - Installing kiwisolver (1.2.0)
  - Installing numpy (1.17.5)
  - Installing pillow (7.2.0)
  - Installing pytz (2020.1)
  - Installing qtpy (1.9.0)
  - Installing requests-oauthlib (1.3.0)
  - Installing werkzeug (1.0.1)
  - Installing widgetsnbextension (3.5.1)
  - Installing absl-py (0.9.0)
  - Installing alabaster (0.7.12)
  - Installing babel (2.8.0)
  - Installing brotli (1.0.7)
  - Installing cloudpickle (1.5.0)
  - Installing docutils (0.16)
  - Installing flask (1.1.2)
  - Installing google-api-core (1.22.0)
  - Installing google-auth-oauthlib (0.4.1)
  - Installing google-crc32c (0.1.0)
  - Installing grpcio (1.30.0)
  - Installing imagesize (1.2.0)
  - Installing ipywidgets (7.5.1)
  - Installing joblib (0.16.0)
  - Installing jupyter-console (6.1.0)
  - Installing locket (0.2.0)
  - Installing markdown (3.2.2)
  - Installing matplotlib (3.3.0)
  - Installing more-itertools (8.4.0)
  - Installing msgpack (1.0.0)
  - Installing pluggy (0.13.1)
  - Installing psutil (5.7.2)
  - Installing py (1.9.0)
  - Installing pyyaml (5.3.1)
  - Installing qtconsole (4.7.5)
  - Installing retrying (1.3.3)
  - Installing scipy (1.4.1)
  - Installing snowballstemmer (2.0.0)
  - Installing sortedcontainers (2.2.2)
  - Installing sphinxcontrib-applehelp (1.0.2)
  - Installing sphinxcontrib-devhelp (1.0.2)
  - Installing sphinxcontrib-htmlhelp (1.0.3)
  - Installing sphinxcontrib-jsmath (1.0.1)
  - Installing sphinxcontrib-qthelp (1.0.3)
  - Installing sphinxcontrib-serializinghtml (1.1.4)
  - Installing tblib (1.7.0)
  - Installing tensorboard-plugin-wit (1.7.0)
  - Installing threadpoolctl (2.1.0)
  - Installing toolz (0.10.0)
  - Installing typing-extensions (3.7.4.2)
  - Installing zict (2.0.0)
  - Installing appdirs (1.4.4)
  - Installing astunparse (1.6.3)
  - Installing bokeh (2.1.1)
  - Installing commonmark (0.9.1)
  - Installing coverage (5.2.1)
  - Installing cython (0.29.21)
  - Installing dash-core-components (1.10.0)
  - Installing dash-html-components (1.0.3)
  - Installing dash-renderer (1.4.1)
  - Installing dash-table (4.7.0)
  - Installing descartes (1.1.0)
  - Installing distributed (2.22.0)
  - Installing flask-compress (1.5.0)
  - Installing fsspec (0.8.0)
  - Installing future (0.18.2)
  - Installing gast (0.3.3)
  - Installing google-cloud-core (1.4.0)
  - Installing google-pasta (0.2.0)
  - Installing google-resumable-media (0.7.0)
  - Installing h5py (2.10.0)
  - Installing jupyter (1.0.0)
  - Installing keras-preprocessing (1.1.2)
  - Installing mccabe (0.6.1)
  - Installing opencv-python (4.3.0.36)
  - Installing opt-einsum (3.3.0)
  - Installing pandas (1.1.0)
  - Installing partd (1.1.0)
  - Installing pathspec (0.8.0)
  - Installing plotly (4.9.0)
  - Installing pycodestyle (2.6.0)
  - Installing pyflakes (2.2.0)
  - Installing pyquaternion (0.9.5)
  - Installing pytest (5.4.3)
  - Installing regex (2020.7.14)
  - Installing scikit-learn (0.23.2)
  - Installing shapely (1.7.0)
  - Installing sphinx (3.1.2)
  - Installing tensorboard (2.3.0)
  - Installing tensorflow-estimator (2.3.0)
  - Installing termcolor (1.1.0)
  - Installing toml (0.10.1)
  - Installing torch (1.4.0)
  - Installing tqdm (4.48.2)
  - Installing typed-ast (1.4.1)
  - Installing wrapt (1.12.1)
  - Installing black (19.10b0)
  - Installing codetiming (1.2.0)
  - Installing dash (1.12.0)
  - Installing dask (2.22.0)
  - Installing flake8 (3.8.3)
  - Installing google-cloud-storage (1.30.0)
  - Installing isort (4.3.21)
  - Installing kornia (0.1.4.post2)
  - Installing nuscenes-devkit (1.0.2)
  - Installing pycocotools (2.0.1)
  - Installing pytest-cov (2.10.0)
  - Installing pytorch-ignite (0.3.0)
  - Installing recommonmark (0.6.0)
  - Installing responses (0.10.15)
  - Installing sphinx-rtd-theme (0.5.0)
  **- Installing tensorboardx (2.1)**
  - Installing tensorflow (2.3.0)
  - Installing torchvision (0.5.0)
  - Installing yacs (0.1.7)
  - Installing datasetinsights (0.1.0)
% pre-commit install
% python -m datasetinsights.cli --local_rank=0 train \
    --config=datasetinsights/configs/faster_rcnn.yaml \
    --data-root=$HOME/data
Traceback (most recent call last):
  File "/Users/alex.zook/.pyenv/versions/3.7.7/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/Users/alex.zook/.pyenv/versions/3.7.7/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/alex.zook/projects/datasetinsights/datasetinsights/datasetinsights/cli.py", line 6, in <module>
    from tensorboardX import SummaryWriter
ModuleNotFoundError: No module named 'tensorboardX'
```

**Anything else you would like to add:**
This was a fresh install and I used the public repo. Also note (bolded above) that tensorboardX seems to be installed.

**Environment:**

- OS + version: macOS 10.15.6
- datasetinsights version: 0.1.0
- _Environment_: (which example environment you used to reproduce the error)
- Other environment settings

**Comment by zookae** [comment]
Tried to `pip install tensorboardX`. This led to a few more pip installs needed:
- tensorboardX
- google.cloud.storage
- pyquaternion
- now I'm missing tensorflow?

**Comment by Saurav-D** [comment]
Hey @zookae it seems to work fine for me on fresh install. Can you try it again?

**Comment by zookae** [comment]
When you say try again do you mean pull a newer version of master? I had tried a fresh install twice by:
a) creating a new conda environment and proceeding.
b) pulling the repo from master, then creating conda environment, then proceeding.
Both failed and still show the same import needs.

My conda version is 4.8.4 and poetry is 1.0.9. I have also tried deleting the lock file to install. Is there any poetry config or other config that might be amiss?

**Comment by zookae** [comment]
Also, by "works" do you mean you can run:
`python -m datasetinsights.cli --local_rank=0 train \
    --config=datasetinsights/configs/faster_rcnn.yaml \
    --data-root=$HOME/data`?

**Comment by zookae** [comment]
Oh, and fwiw the current error I'm hitting (after doing a handful of pip installs) is:
```
(dins-dev) alex.zook@alex datasetinsights % python -m datasetinsights.cli --local_rank=0 train \
    --config=datasetinsights/configs/faster_rcnn.yaml \
    --data-root=$HOME/data
Traceback (most recent call last):
  File "/Users/alex.zook/.pyenv/versions/3.7.7/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/Users/alex.zook/.pyenv/versions/3.7.7/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/alex.zook/projects/datasetinsights/datasetinsights/cli.py", line 15, in <module>
    from .estimators import Estimator
  File "/Users/alex.zook/projects/datasetinsights/datasetinsights/estimators/__init__.py", line 2, in <module>
    from .deeplab import DeeplabV3
  File "/Users/alex.zook/projects/datasetinsights/datasetinsights/estimators/deeplab.py", line 7, in <module>
    from ignite.metrics import Loss
ModuleNotFoundError: No module named 'ignite.metrics'
```

**Comment by Saurav-D** [comment]
I had similar issue, if I remember correctly it was something related to my conda installation. Can you try reinstalling anaconda and try installation again in a new environment ?

**Comment by zookae** [comment]
per our conversation i uninstalled pyenv entirely. was able to get install to work and ran the suggested command. here's the error track:
```
python -m datasetinsights.cli --local_rank=0 train \
    --config=datasetinsights/configs/faster_rcnn.yaml \
    --data-root=$HOME/data
Unable to revert mtime: /Library/Fonts
INFO | 2020-08-20 12:17:25 | datasetinsights.torch_distributed | MainThread | Not using distributed mode
INFO | 2020-08-20 12:17:25 | __main__ | MainThread | Run command: train with config: backbone: resnet50
estimator: FasterRCNN
metrics:
  APIOU50:
    name: AveragePrecisionIOU50
  mAP:
    name: MeanAveragePrecisionAverageOverIOU
  mAPIOU50:
    name: MeanAveragePrecisionIOU50
  mAR:
    name: MeanAverageRecallAverageOverIOU
num_classes: 91
optimizer:
  args:
    lr: 0.0002
  name: Adam
pretrained: False
pretrained_backbone: True
synchronize_metrics: True
system:
  auth_token: None
  data_root: /Users/alex.zook/data
  distributed: False
  dryrun: False
  gpus_per_node: 1
  logdir: None
  metricsdir: /Users/alex.zook/projects/datasetinsights/metrics/20200820-121707
  metricsfilename: mlpipeline-metrics.json
  no_cuda: False
  val_interval: 1
  verbose: False
  workers: 0
task: object_detection
test:
  batch_size: 4
  dataset:
    args:
      split: val
      version: 2017
    name: CocoDetection
train:
  accumulation_steps: 8
  batch_size: 4
  dataset:
    args:
      split: train
      version: 2017
    name: CocoDetection
  epochs: 26
  log_frequency: 1000
val:
  batch_size: 4
  dataset:
    args:
      split: val
      version: 2017
    name: CocoDetection

INFO | 2020-08-20 12:17:25 | datasetinsights.estimators.faster_rcnn | MainThread | initializing faster rcnn
INFO | 2020-08-20 12:17:25 | datasetinsights.estimators.faster_rcnn | MainThread | gpu: 0, rank: 0
INFO | 2020-08-20 12:17:27 | datasetinsights.datasets.coco | MainThread | checking for local copy of data
loading annotations into memory...
Done (t=13.84s)
creating index...
index created!
INFO | 2020-08-20 12:17:45 | datasetinsights.datasets.coco | MainThread | checking for local copy of data
loading annotations into memory...
Done (t=0.48s)
creating index...
index created!
Traceback (most recent call last):
  File "/Users/alex.zook/anaconda3/envs/dins-dev/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/Users/alex.zook/anaconda3/envs/dins-dev/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/alex.zook/projects/datasetinsights/datasetinsights/cli.py", line 241, in <module>
    run(command, cfg)
  File "/Users/alex.zook/projects/datasetinsights/datasetinsights/cli.py", line 202, in run
    estimator.train()
  File "/Users/alex.zook/projects/datasetinsights/datasetinsights/estimators/faster_rcnn.py", line 109, in train
    label_mappings = train_dataset.label_mappings
AttributeError: 'CocoDetection' object has no attribute 'label_mappings'
```

is that tied to some other issue?

**Comment by Saurav-D** [comment]
Yes, that is some other issue. We'll update it. For now, we can close this issue.
